/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfases;

import java.awt.BorderLayout;
import javax.swing.JTabbedPane;

/**
 *
 * @author ADMIN_01
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PANELPRINCIPAL = new javax.swing.JPanel();
        carrerasBtn = new javax.swing.JButton();
        institutoBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 100));

        PANELPRINCIPAL.setBackground(new java.awt.Color(255, 255, 255));
        PANELPRINCIPAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(PANELPRINCIPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 780, 500));

        carrerasBtn.setText("Carreras");
        carrerasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrerasBtnActionPerformed(evt);
            }
        });
        jPanel1.add(carrerasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 40));

        institutoBTN.setText("Institucion");
        institutoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institutoBTNActionPerformed(evt);
            }
        });
        jPanel1.add(institutoBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carrerasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrerasBtnActionPerformed
        Carreras ca = new Carreras();
        ca.setSize(770, 500);
        ca.setLocation(0, 0);
        carrerasBtn.removeAll();
        carrerasBtn.add(ca, BorderLayout.CENTER);
        carrerasBtn.revalidate();
        carrerasBtn.repaint();


    }//GEN-LAST:event_carrerasBtnActionPerformed

    private void institutoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institutoBTNActionPerformed
        Institucion in = new Institucion();
        in.setSize(770, 500);
        in.setLocation(0, 0);
        carrerasBtn.removeAll();
        carrerasBtn.add(in, BorderLayout.CENTER);
        carrerasBtn.revalidate();
        carrerasBtn.repaint();

        

        // Establecer el tamaño y la ubicación del panel Institucion
        in.setSize(770, 500);
        in.setLocation(0, 0);

        // Eliminar todos los componentes del panel principal
        PANELPRINCIPAL.removeAll();

        // Agregar el panel Institucion al centro del panel principal
        PANELPRINCIPAL.add(in, BorderLayout.CENTER);

        // Validar y repintar el panel principal para que se actualice con el nuevo componente
        PANELPRINCIPAL.revalidate();
        PANELPRINCIPAL.repaint();


    }//GEN-LAST:event_institutoBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANELPRINCIPAL;
    private javax.swing.JButton carrerasBtn;
    private javax.swing.JButton institutoBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
